---

COMMON_EMAIL_HOST_USER_VAULT: ''
COMMON_EMAIL_HOST_PASSWORD_VAULT: ''

EDXAPP_YOUTUBE_API_KEY: ''

NEWRELIC_LICENSE_KEY: ''
COMMON_SENTRY_DSN: ''

COMMON_STAFF_PASSWORD: 'XXXXXXXXXXXXXXXXXXXXXX'
EDXAPP_EDX_API_KEY: 'XXXXXXXXXXXXXXXXXXXXXX'
EDXAPP_STAFF_PASSWORD: "{{ COMMON_STAFF_PASSWORD }}"

EDXAPP_SOCIAL_AUTH_OAUTH_SECRETS:
  google-oauth2: 'XXXXXXXXXXXXXXXXXXXXXXXX'
  facebook: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
  linkedin-oauth2: 'XXXXXXXXXXXXXXXX'

EDXAPP_OAUTH_ENFORCE_SECURE: true

EDXAPP_MYSQL_PASSWORD_ADMIN: 'XXXXXXXXXXXXXXXXXXXXXX'
EDXAPP_MYSQL_USER_ADMIN: 'root'
EDXAPP_MYSQL_DB_NAME: 'edxapp'
EDXAPP_MYSQL_CSMH_DB_NAME: 'edxapp_csmh'
EDXAPP_MYSQL_CSMH_USER: 'edxapp_cmsh001'
COMMON_MYSQL_MIGRATE_USER: 'migrate'
COMMON_MYSQL_ADMIN_USER: 'admin'
XQUEUE_MYSQL_DB_NAME: 'xqueue'
XQUEUE_MYSQL_USER: 'xqueue'
EDXAPP_MYSQL_USER: 'edxapp001'
COMMON_MYSQL_READ_ONLY_USER: 'read_only'

XQUEUE_DJANGO_USERS:
  lms: 'XXXXXXXXXXXXXXXXXXXXXX'
EDXAPP_XQUEUE_DJANGO_AUTH:
  username: 'lms'
  password: "{{ XQUEUE_DJANGO_USERS.lms }}"

EDXAPP_MONGO_DB_NAME: 'edxapp'
MONGO_ADMIN_USER: 'admin'
MONGO_ADMIN_PASSWORD: 'XXXXXXXXXXXXXXXXXXXXXX'
mongo_admin_password: "{{ MONGO_ADMIN_PASSWORD }}"
COMMON_MONGO_READ_ONLY_USER: 'read_only'
EDXAPP_MONGO_PASSWORD: 'XXXXXXXXXXXXXXXXXXXXXX'
EDXAPP_MONGO_USER: 'edxapp'
COMMON_MONGO_READ_ONLY_PASS: 'XXXXXXXXXXXXXXXXXXXXXX'
MONGO_CS_COMMENTS_SERVICE_DB_NAME: 'cs_comments_service'
FORUM_MONGO_USER: 'cs_comments_service'
FORUM_MONGO_PASSWORD: 'XXXXXXXXXXXXXXXXXXXXXX'

MONGO_USERS:
  - user: "{{ FORUM_MONGO_USER }}"
    password: "{{ FORUM_MONGO_PASSWORD }}"
    database: "{{ MONGO_CS_COMMENTS_SERVICE_DB_NAME }}"
    roles: 'readWrite'
  - user: "{{ EDXAPP_MONGO_USER }}"
    password: "{{ EDXAPP_MONGO_PASSWORD }}"
    database: 'edxapp'
    roles: 'readWrite'
  - user: "{{ EDXAPP_MONGO_USER }}"
    password: "{{ EDXAPP_MONGO_PASSWORD }}"
    database: 'xlog'
    roles: 'readWrite'

RABBIT_ADMIN_PASSWORD: 'XXXXXXXXXXXXXXXXXXXXXXXX'
RABBIT_USERS:
  - name: 'admin'
    password: "{{ RABBIT_ADMIN_PASSWORD }}"
  - name: 'celery'
    password: "{{ EDXAPP_CELERY_PASSWORD }}"
  - name: 'ecommercecelery'
    password: "{{ ECOMMERCE_BROKER_PASSWORD }}"
  - name: 'ecomworkercelery'
    password: "{{ ECOMMERCE_WORKER_BROKER_PASSWORD }}"

CERTS_XQUEUE_AUTH_USER: 'edx'
CERTS_XQUEUE_AUTH_PASS: 'edx'
CERTS_QUEUE_USER: 'lms'
CERTS_QUEUE_PASS: "{{ XQUEUE_DJANGO_USERS.lms }}"

EDXAPP_EDXAPP_SECRET_KEY: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'

ANALYTICS_PIPELINE_OUTPUT_DATABASE_PASSWORD: 'XXXXXXXXXXXXXXXXXXXXXXXX'
ANALYTICS_SCHEDULE_MASTER_SSH_CREDENTIAL_PASSPHRASE: 'XXXXXXXXXXXXXXXXXXXXXXXX'
COMMON_HTPASSWD_PASS: 'XXXXXXXXXXXXXXXXXXXXXXXX'
COMMON_HTPASSWD_USER: 'XXXXXXXXXXXXXXXXXXXXXXXX'
COMMON_MYSQL_ADMIN_PASS: 'XXXXXXXXXXXXXXXXXXXXXXXX'
COMMON_MYSQL_MIGRATE_PASS: 'XXXXXXXXXXXXXXXXXXXXXXXX'
COMMON_MYSQL_READ_ONLY_PASS: 'XXXXXXXXXXXXXXXXXXXXXXXX'
CREDENTIALS_MYSQL_PASSWORD: 'XXXXXXXXXXXXXXXXXXXXXXXX'

FORUM_API_KEY: 'XXXXXXXXXXXXXXXXXXXXXXXX'
DISCOVERY_MYSQL_PASSWORD: 'XXXXXXXXXXXXXXXXXXXXXXXX'
ECOMMERCE_DATABASE_PASSWORD: 'XXXXXXXXXXXXXXXXXXXXXXXX'
EDXAPP_CELERY_PASSWORD: 'XXXXXXXXXXXXXXXXXXXXXXXX'
ECOMMERCE_WORKER_BROKER_USERNAME: 'ecomworkercelery'
ECOMMERCE_WORKER_BROKER_PASSWORD: 'XXXXXXXXXXXXXXXXXXXXXXXX'
ECOMMERCE_BROKER_USERNAME: 'ecommercecelery'
ECOMMERCE_BROKER_PASSWORD: 'XXXXXXXXXXXXXXXXXXXXXXXX'
ECOMMERCE_SECRET_KEY: "{{ EDXAPP_EDXAPP_SECRET_KEY }}"
ECOMMERCE_SOCIAL_AUTH_EDX_OIDC_KEY: 'XXXXXXXXXXXXXXXXXXXX'
ECOMMERCE_SOCIAL_AUTH_EDX_OIDC_SECRET: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'

EDXAPP_COMMENTS_SERVICE_KEY: "{{ FORUM_API_KEY }}"
EDXAPP_MYSQL_CSMH_PASSWORD: 'XXXXXXXXXXXXXXXXXXXXXXXX'
EDXAPP_MYSQL_PASSWORD: 'XXXXXXXXXXXXXXXXXXXXXXXX'
EDXAPP_MYSQL_REPLICA_PASSWORD: "{{ EDXAPP_MYSQL_PASSWORD }}"
EDXAPP_MYSQL_REPLICA_USER: "{{ EDXAPP_MYSQL_USER }}"
EDXAPP_MYSQL_PASSWORD_READ_ONLY: 'XXXXXXXXXXXXXXXXXXXXXXXX'
FLOWER_BROKER_PASSWORD: 'XXXXXXXXXXXXXXXXXXXXXXXX'
HIVE_METASTORE_DATABASE_PASSWORD: 'XXXXXXXXXXXXXXXXXXXXXXXX'
INSIGHTS_DATABASE_PASSWORD: 'XXXXXXXXXXXXXXXXXXXXXXXX'
INSIGHTS_SECRET_KEY: "{{ EDXAPP_EDXAPP_SECRET_KEY }}"
INSIGHTS_OAUTH2_KEY: 'XXXXXXXXXXXXXXXXXXXX'
INSIGHTS_OAUTH2_SECRET: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
JENKINS_ANALYTICS_GITHUB_CREDENTIAL_PASSPHRASE: 'XXXXXXXXXXXXXXXXXXXXXXXX'
JENKINS_ANALYTICS_USER_PASSWORD_PLAIN: 'XXXXXXXXXXXXXXXXXXXXXXXX'
MARIADB_CLUSTER_PASSWORD_ADMIN: 'XXXXXXXXXXXXXXXXXXXXXXXX'
NOTIFIER_COMMENT_SERVICE_API_KEY: "{{ FORUM_API_KEY }}"
NOTIFIER_USER_SERVICE_HTTP_AUTH_PASS: 'XXXXXXXXXXXXXXXXXXXXXXXX'
PROGRAMS_DATABASE_PASSWORD: 'XXXXXXXXXXXXXXXXXXXXXXXX'
REDIS_PASSWORD: 'XXXXXXXXXXXXXXXXXXXXXXXX'
SPLUNKFORWARDER_PASSWORD: 'XXXXXXXXXXXXXXXXXXXXXXXX'
SPLUNK_SSL_PASSWORD: 'XXXXXXXXXXXXXXXXXXXXXXXX'
SWIFT_LOG_SYNC_PASSWORD: 'XXXXXXXXXXXXXXXXXXXXXXXX'
XQUEUE_BASIC_AUTH_PASSWORD: 'XXXXXXXXXXXXXXXXXXXXXXXX'
XQUEUE_BASIC_AUTH_USER: 'XXXXXXXXXXXXXXXXXXXXXXXX'
XQUEUE_MYSQL_PASSWORD: 'XXXXXXXXXXXXXXXXXXXXXXXX'
XSY_PASSWORD: 'XXXXXXXXXXXXXXXXXXXXXXXX'
CREDENTIALS_SECRET_KEY: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
DISCOVERY_SECRET_KEY: "{{ EDXAPP_EDXAPP_SECRET_KEY }}"
EDX_NOTES_API_SECRET_KEY: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
EDX_NOTES_API_CLIENT_ID: 'XXXXXXXXXXXXXXXXXXXXX'
EDX_NOTES_API_CLIENT_SECRET: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
EDX_NOTES_API_MYSQL_DB_PASS: 'XXXXXXXXXXXXXXXXXXXX'
EDXAPP_PROFILE_IMAGE_SECRET_KEY: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
NOTIFIER_LMS_SECRET_KEY: "{{ EDXAPP_EDX_API_KEY }}"
NOTIFIER_USER_SERVICE_API_KEY: "{{ EDXAPP_EDX_API_KEY }}"
PROGRAMS_SECRET_KEY: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
COMMON_JWT_AUDIENCE: 'XXXXXXXXXXXXXXXXXXXXXXXX'
COMMON_JWT_SECRET_KEY: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
DISCOVERY_SOCIAL_AUTH_EDX_OIDC_KEY: 'XXXXXXXXXXXXXXXXXXXXXXXX'
DISCOVERY_SOCIAL_AUTH_EDX_OIDC_SECRET: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
VIDEO_PIPELINE_BASE_SECRET_KEY: "{{ EDXAPP_EDXAPP_SECRET_KEY }}"
VEDA_WEB_FRONTEND_SOCIAL_AUTH_EDX_OIDC_KEY: 'XXXXXXXXXXXXXXXXXXXX'
VEDA_WEB_FRONTEND_SOCIAL_AUTH_EDX_OIDC_SECRET: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
VIDEO_PIPELINE_BASE_OAUTH_CLIENT_ID: 'XXXXXXXXXXXXXXXXXXXXXX'
VIDEO_PIPELINE_BASE_OAUTH_CLIENT_SECRET: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
EDXAPP_RETIRED_USER_SALTS:
  - 'XXXXXXXXXXXXXXXXXXXXXXXX'
  - 'XXXXXXXXXXXXXXXXXXXXXXXX'
EDXAPP_RETIREMENT_DOT_CLIENT_ID: 'XXXXXXXXXXXXXXXXXXXXXXXXX'
EDXAPP_RETIREMENT_DOT_CLIENT_SECRET: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
RABBIT_ERLANG_COOKIE: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
CREDENTIALS_SOCIAL_AUTH_EDX_OIDC_KEY: 'XXXXXXXXXXXXXXXXXXXXXXXXXXX'
CREDENTIALS_SOCIAL_AUTH_EDX_OIDC_SECRET: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'

# must be set to empty string until investigation of 'use-asymmetric-jwts' is not done
COMMON_JWT_PUBLIC_SIGNING_JWK_SET: ''
EDXAPP_JWT_PRIVATE_SIGNING_JWK: ''
# TODO: RTFM
# https://openedx.atlassian.net/browse/OSPR-2787
# https://github.com/edx/edx-platform/blob/master/openedx/core/djangoapps/oauth_dispatch/docs/decisions/0008-use-asymmetric-jwts.rst
# https://github.com/edx/edx-platform/blob/master/openedx/core/djangoapps/oauth_dispatch/docs/decisions/0003-use-jwt-as-oauth-tokens-remove-openid-connect.rst
EXAMPLE_COMMON_JWT_PUBLIC_SIGNING_JWK_SET: '{"keys": [{"kid": "test_key", "e": "AQAB", "kty": "RSA", "n": "z4Gum0m6T0CcMN6h0CGvJIOSuS96Jo77WbYGnc5jQyWBC3LMv1o_v10u5xb7uwTGVkp56E21mnHWso3T7xAaXJiAGN5tcYJRnOVFvhTDJT3CjZYoU5HI-c81OiMEYs4r7sT__5TyGsSRvEH3LCO6oe8meAESFvOywjDGKeTHGFT2b8xRCD0HUokp6u8DBR1hV_JogZHjJA5yWt3HC9uuSQupVHPhAgdcOHmN0_Teejvxh1tMEL9K6flviIsxbsLoLDyV2TKN02EC8LXLhvluU8r69nujaJmjnmclSjILMQC2FdzH04r41a6w8ocTHOcVIifViWJxeAKsXMfkWRH0HQ"}]}'
EXAMPLE_EDXAPP_JWT_PRIVATE_SIGNING_JWK: '{"e": "AQAB", "d": "CsvOu5YZqytrpPBEX3mNLPtqfBeQBacNRUTe8cFt8S2nmeKia_dEV07AFLZhqQCN2Cn-TzuRzgQLvVT7OJYwJO6rRX_3Fj-HQwA7wXC_mXWt5GNyXCy61eJ1vL1bKk_bQcw-nHvRn9pn0bFl7IY8XNX-PKKjoA2UWJ2khcP5JtcWudoKoFFWKj9VffO-7VFhD7K08V6LoYFFukzee8ezoSzJrUVy8vLeO7QYia8eutWN9_YKbOLo_1ZXeiKsMA8_2Qn0Lo2a-e5cUux1z8s-XUJPtiEHgIXebYysFdzbvzHp1Hu4-ziDsmlDCI7cbMQ0b6SLXK-uKjCWtDNDoVLaQ", "n": "z4Gum0m6T0CcMN6h0CGvJIOSuS96Jo77WbYGnc5jQyWBC3LMv1o_v10u5xb7uwTGVkp56E21mnHWso3T7xAaXJiAGN5tcYJRnOVFvhTDJT3CjZYoU5HI-c81OiMEYs4r7sT_5TyGsSRvEH3LCO6oe8meAESFvOywjDGKeTHGFT2b8xRCD0HUokp6u8DBR1hV_JogZHjJA5yWt3HC9uuSQupVHPhAgdcOHmN0_Teejvxh1tMEL9K6flviIsxbsLoLDyV2TKN02EC8LXLhvluU8r69nujaJmjnmclSjILMQC2FdzH04r41a6w8ocTHOcVIifViWJxeAKsXMfkWRH0HQ", "q": "_BwiDux-WgCLp4eCg5BfVcB-kmKWBtdHASS-ZFXdpquDHsYl1VfBAPFZ4Hq2V2ZHdZJ7SoPfIod4SlQ4GCg8LRpSeHjK-FIulbfKd_ZjtCGKpwbDrOzXmbwVfATR-A-KESXMtS0d8iSYQdC0xXZGjLxAqzT_iDfbcXg9bQQvQiU", "p": "0rVcLYwfMTCeKPd_uiTkTpf6B3rJjsb6I_f4BeIuWYkePaIY8sPyXgNIuiW1pYtr7j59NfrEDKmA6k6I3lI5e0mjTIG8oHEiGo8eQdTxYcfwWo1dTtSitpSBazcjKkdEtM81k-PgSstP_pFshzQ0yxUR8oaestz5wAB6LwGr_Jk", "kid": "test_key", "kty": "RSA"}'

EDXAPP_GIT_IDENTITY: "{{ RG_COMMON_GIT_IDENTITY }}"
