---

# COMMON_SENTRY_DSN must be stored in secrets.yml
COMMON_SENTRY_ENVIRONMENT: "{{ COMMON_ENVIRONMENT }}"

COMMON_ENABLE_CERTS: False
COMMON_ENABLE_XQUEUE: "{{ COMMON_ENABLE_CERTS }}"
COMMON_ENABLE_FORUM: True
COMMON_ENABLE_CREDENTIALS: False
COMMON_ENABLE_DISCOVERY: False
COMMON_ENABLE_SHOPPING_CART: False
COMMON_ENABLE_ECOMMERCE: False
COMMON_ENABLE_ANALYTICS_API: False
COMMON_ENABLE_INSIGHTS: False
COMMON_ENABLE_CELERYBEAT: "{{ COMMON_RG_INSTRUCTOR_ANALYTICS_ENABLE }}"
COMMON_ENABLE_ACCOUNT_DELETION: False
JOURNALS_ENABLED: False
COMMON_RG_INSTRUCTOR_ANALYTICS_ENABLE: False
COMMON_ENABLE_EDXNOTES: False
COMMON_ENABLE_EDXSEARCH: True
COMMON_ENABLE_BACKUPS_DUPLICITY: False
COMMON_ENABLE_BACKUPS_AWS_SNAPSHOTS: False
COMMON_ENABLE_BACKUPS_AZURE_RECOVERY_VAULT: False
COMMON_ENABLE_FILEBEAT: False
COMMON_ENABLE_SENTRY: False
