---

EDXAPP_EMAIL_HOST: "email-smtp.eu-west-1.amazonaws.com"
EDXAPP_EMAIL_HOST_USER: "AKIAJ4B4Z5OYCW3F2QCA"
EDXAPP_EMAIL_HOST_PASSWORD: "Aub+NM1jxgZLEHa0d85MNjPRR/XRTQXuZZXwCtP45c52"
EDXAPP_EMAIL_PORT: 587
EDXAPP_EMAIL_USE_TLS: True
EDXAPP_DEFAULT_FROM_EMAIL: "devops@raccoongang.com"

EDXAPP_YOUTUBE_API_KEY: ""

NEWRELIC_LICENSE_KEY: ""
COMMON_RG_SENTRY_DSN: 'https://4cb334255e6c4f7786cc28cf5b4dd26c@sentry.raccoongang.com/10'

EDXAPP_STAFF_PASSWORD: "t9jlm61zUqof7hjv02Yf99"
EDXAPP_EDX_API_KEY: "666s56mEUjR3n963eQVDDM"

EDXAPP_SOCIAL_AUTH_OAUTH_SECRETS:
  google-oauth2: "KszRLZBq3mOCuqadN3oB9DBC"
  facebook: "65d38cb25f0ea7374463c736d6082e71"
  linkedin-oauth2: "mqShEvu0IO6biOQn"

EDXAPP_OAUTH_ENFORCE_SECURE: true

EDXAPP_MYSQL_PASSWORD_ADMIN: "ggnaBpzAhYww3AtxDdIsaa"
EDXAPP_MYSQL_USER_ADMIN: root
EDXAPP_MYSQL_DB_NAME: edxapp
EDXAPP_MYSQL_CSMH_DB_NAME: "edxapp_csmh"
EDXAPP_MYSQL_CSMH_USER: 'edxapp_cmsh001'
COMMON_MYSQL_MIGRATE_USER: "migrate"
COMMON_MYSQL_ADMIN_USER: "admin"
XQUEUE_MYSQL_DB_NAME: "xqueue"
XQUEUE_MYSQL_USER: "xqueue"
EDXAPP_MYSQL_USER: "edxapp001"
COMMON_MYSQL_READ_ONLY_USER: "read_only"

XQUEUE_DJANGO_USERS:
  lms: "T35NKRWM1tDyfF978n6LRR"
EDXAPP_XQUEUE_DJANGO_AUTH:
  username: "lms"
  password: "{{ XQUEUE_DJANGO_USERS.lms }}"

EDXAPP_MONGO_DB_NAME: 'edxapp'
MONGO_ADMIN_USER: 'admin'
COMMON_MONGO_READ_ONLY_USER: "read_only"
EDXAPP_MONGO_PASSWORD: "4fxGtQZtoROYJxbXxigTW6"
EDXAPP_MONGO_USER: 'edxapp'
MONGO_CS_COMMENTS_SERVICE_DB_NAME: "cs_comments_service"
MONGO_USERS:
  - user: "{{ FORUM_MONGO_USER }}"
    password: "{{ FORUM_MONGO_PASSWORD }}"
    database: "{{ MONGO_CS_COMMENTS_SERVICE_DB_NAME }}"
    roles: readWrite
  - user: "{{ EDXAPP_MONGO_USER }}"
    password: "{{ EDXAPP_MONGO_PASSWORD }}"
    database: edxapp
    roles: readWrite
  - user: "{{ EDXAPP_MONGO_USER }}"
    password: "{{ EDXAPP_MONGO_PASSWORD }}"
    database: xlog
    roles: readWrite

XQUEUE_RABBITMQ_USER: "edx"
RABBIT_ADMIN_PASSWORD: "CGZObcb1iJoKaUEDeCTCFg"
RABBIT_USERS:
  - name: 'admin'
    password: "{{ RABBIT_ADMIN_PASSWORD }}"
  - name: 'edx'
    password: "{{ XQUEUE_RABBITMQ_PASS }}"
  - name: 'celery'
    password: "{{ EDXAPP_CELERY_PASSWORD }}"
  - name: 'ecommercecelery'
    password: "{{ ECOMMERCE_BROKER_PASSWORD }}"
  - name: 'ecomworkercelery'
    password: "{{ ECOMMERCE_WORKER_BROKER_PASSWORD }}"

CERTS_XQUEUE_AUTH_USER: "edx"
CERTS_XQUEUE_AUTH_PASS: "edx"
CERTS_QUEUE_USER: "lms"
CERTS_QUEUE_PASS: "{{ XQUEUE_DJANGO_USERS.lms }}"

FORUM_MONGO_USER: 'cs_comments_service'
FORUM_MONGO_PASSWORD: "UCNgfnXxdTAAlSjTL8vEgK"

ANALYTICS_PIPELINE_OUTPUT_DATABASE_PASSWORD: "dfO1vXvAwJqY3SJWg2vdAA"
ANALYTICS_SCHEDULE_MASTER_SSH_CREDENTIAL_PASSPHRASE: "qLCzgLfFVPtkg6HklV0ILk"
COMMON_HTPASSWD_PASS: "QAWoOU6hCRCoh3t2Jw4WzW"
COMMON_HTPASSWD_USER: "eK5vTb98f2tG9UPtPiCvGo"
COMMON_MONGO_READ_ONLY_PASS: "LgnLHCAxWyU5gBLEZErJKd"
COMMON_MYSQL_ADMIN_PASS: "D0fOgDDVy1rToqRXW99BB5"
COMMON_MYSQL_MIGRATE_PASS: "E4T5p1bRgQTNvMzADALjC3"
COMMON_MYSQL_READ_ONLY_PASS: "bUus3koJ8lyZUqMY8ZB8dj"
CREDENTIALS_MYSQL_PASSWORD: "hx56vmJiBiEZSms3eWIAjm"

FORUM_API_KEY: "1kunFvnEB76moVAOMpfOJX"
DISCOVERY_MYSQL_PASSWORD: "R3lRRzR0sQALasjVi4i0zg"
ECOMMERCE_DATABASE_PASSWORD: "FxmaH33QK040x2apikWxY1"
EDXAPP_CELERY_PASSWORD: "9hJuaUpRgpZqqtM43mMSSP"
ECOMMERCE_WORKER_BROKER_USERNAME: 'ecomworkercelery'
ECOMMERCE_WORKER_BROKER_PASSWORD: "UcRcYmfTFt4MJxWmM11xvn"
ECOMMERCE_BROKER_USERNAME: 'ecommercecelery'
ECOMMERCE_BROKER_PASSWORD: "Gr3liQIiCDPfRqSKDY2vob"

EDXAPP_COMMENTS_SERVICE_KEY: "{{ FORUM_API_KEY }}"
EDXAPP_MYSQL_CSMH_PASSWORD: "jtjHIoXUuYqusCdE7VgHVI"
EDXAPP_MYSQL_PASSWORD: "Qkf38jLrCdNlDE2mLWFQW7"
EDXAPP_MYSQL_REPLICA_PASSWORD: "{{ EDXAPP_MYSQL_PASSWORD }}"
EDXAPP_MYSQL_REPLICA_USER: "{{ EDXAPP_MYSQL_USER }}"
EDXAPP_MYSQL_PASSWORD_READ_ONLY: "e2kTCR2nVer9VITVciFWXA"
FLOWER_BROKER_PASSWORD: "fjAvMuOEEnfXdkIkc9ViKs"
HIVE_METASTORE_DATABASE_PASSWORD: "8hLVUKl93ExlF7ZyZaKQpo"
INSIGHTS_DATABASE_PASSWORD: "K2J7gHUvZbT7W2yo1ThrSy"
JENKINS_ANALYTICS_GITHUB_CREDENTIAL_PASSPHRASE: "zkiZLDZ3xQ4zzVfTWJwgCq"
JENKINS_ANALYTICS_USER_PASSWORD_PLAIN: "CDdKdVNmw56FIPs2UGA7cL"
MARIADB_CLUSTER_PASSWORD_ADMIN: "F1dxTtmxfvg3Zka7wcCcXC"
MONGO_ADMIN_PASSWORD: "yjjOR7toV7DcH8OD4qoXIm"
mongo_admin_password: "{{ MONGO_ADMIN_PASSWORD }}"
NOTIFIER_COMMENT_SERVICE_API_KEY: "{{ FORUM_API_KEY }}"
NOTIFIER_USER_SERVICE_HTTP_AUTH_PASS: "jDyj2uGVYA6ZtuIxTJFhWq"
PROGRAMS_DATABASE_PASSWORD: "TG29qrL1PSq1VxcpYuIacD"
REDIS_PASSWORD: "m15KfcfGL8ji1IAw7q3OvA"
SPLUNKFORWARDER_PASSWORD: "MFbGAwvcsxVyspTvRuB00v"
SPLUNK_SSL_PASSWORD: "95HXtrAOJqUimxbrlK9FKQ"
SWIFT_LOG_SYNC_PASSWORD: "6GkgTvsOPBIViIzYSA1pLm"
XQUEUE_BASIC_AUTH_PASSWORD: "aPDVBxTqPo5fQ2fkCdiWBI"
XQUEUE_BASIC_AUTH_USER: "GbC4yqfvR91m1DmODMxvFL"
XQUEUE_MYSQL_PASSWORD: "4NcgrzVPKXH6q9I82UgL5F"
XQUEUE_RABBITMQ_PASS: "jpVAXdlXFPaoypQWZesKPN"
XSY_PASSWORD: "pmzHtpjjNUsJUhBzxgc0pZ"
CREDENTIALS_SECRET_KEY: "X24E7SayuBlgTxYJ1N7x7zHA6CGesvo3VgjuZCPkxyd"
DISCOVERY_SECRET_KEY: "{{ EDXAPP_EDXAPP_SECRET_KEY }}"
ECOMMERCE_SECRET_KEY: "va1OcmMHJESACuMlzgEspyTY3U5rsSg8kB1Tot2VwIL"
EDX_NOTES_API_SECRET_KEY: "eNXlYStfxriMSt0bfKs1C29AKc9qot0Ass5H2niGJpO"
EDX_NOTES_API_CLIENT_ID: "56508419C78EC41C71d6"
EDX_NOTES_API_CLIENT_SECRET: "735078aaa8b7d5d014e29a603514ef97f6155f1e"
EDX_NOTES_API_MYSQL_DB_PASS: "EIgh234CHIeBo9ai0ab9"
EDXAPP_EDXAPP_SECRET_KEY: "o4HxYM1wna5akSzx2ZSKstVWTUt8LEr3vH6SMeKhkoM"
EDXAPP_PROFILE_IMAGE_SECRET_KEY: "1W4vhUHNYYkWpebphE1GT4tjparI9wtlnqFp7VOj2HB"
NOTIFIER_LMS_SECRET_KEY: "{{ EDXAPP_EDX_API_KEY }}"
NOTIFIER_USER_SERVICE_API_KEY: "{{ EDXAPP_EDX_API_KEY }}"
PROGRAMS_SECRET_KEY: "i5l0kWK7vp1u9gWzDBUEqBAFFmSC7U8fHa98IzL1RwE"
COMMON_JWT_AUDIENCE: "ChnsMgrE2DghRm6gFiFTEMdMS26KXIb2Q1jgT9m9f0t"
COMMON_JWT_SECRET_KEY: "GttqWe6baANLKklly91W8UkLOKPdbunbK4LKA8u98Fy"
EDXAPP_RETIRED_USER_SALTS:
  - "ohzo4aixe6daeMeeg5eengae"
  - "Ooloo6eequ5AiQuohzah1Wei"
EDXAPP_RETIREMENT_DOT_CLIENT_ID: "XXXImcpvzCSvJ1UjjEyOa0uoaNpZA2UcT596eBcp"
EDXAPP_RETIREMENT_DOT_CLIENT_SECRET: "XXXZbhOygUHlAGfkn4nKZvzvxSBLjTyNpVqLsAYkOfdyoJXHYBDFL4fyDEagr39XBiM4FPvNvFOcApOhysAa8pyJO4v5R5PLUVmVfOhablRj6g8CZhAiP7Ghd3zz9v2b"
